# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: banking.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='banking.proto',
  package='app',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rbanking.proto\x12\x03\x61pp\"/\n\x0eWriteSetStruct\x12\x0c\n\x04S_ID\x18\x01 \x01(\r\x12\x0f\n\x07ProgrID\x18\x02 \x01(\x04\"?\n\x0fWriteSetRequest\x12\x0c\n\x04S_ID\x18\x01 \x01(\r\x12\x0f\n\x07LAST_ID\x18\x02 \x01(\x04\x12\r\n\x05\x43lock\x18\x03 \x01(\x04\"#\n\x10\x43heckSetResponse\x12\x0f\n\x07IS_LAST\x18\x01 \x01(\x08\"@\n\x10WriteSetResponse\x12\r\n\x05\x43lock\x18\x01 \x01(\x04\x12\x0c\n\x04S_ID\x18\x02 \x01(\r\x12\x0f\n\x07ProgrID\x18\x03 \x01(\x04\"\x9c\x01\n\x12MsgDeliveryRequest\x12\x0e\n\x06REQ_ID\x18\x01 \x01(\r\x12\x1a\n\x02OP\x18\x02 \x01(\x0e\x32\x0e.app.Operation\x12\x0e\n\x06\x41mount\x18\x03 \x01(\x01\x12\x0e\n\x06S_TYPE\x18\x04 \x01(\r\x12\x0c\n\x04S_ID\x18\x05 \x01(\r\x12\x0c\n\x04\x44_ID\x18\x06 \x01(\r\x12\r\n\x05\x43lock\x18\x07 \x01(\x04\x12\x0f\n\x07ProgrID\x18\x08 \x01(\x04\"\x87\x01\n\x13MsgDeliveryResponse\x12\x0e\n\x06REQ_ID\x18\x01 \x01(\r\x12\x1b\n\x02RC\x18\x02 \x01(\x0e\x32\x0f.app.ReturnCode\x12\x0e\n\x06\x41mount\x18\x03 \x01(\x01\x12\r\n\x05\x43lock\x18\x04 \x01(\x04\x12$\n\x07WriteID\x18\x05 \x01(\x0b\x32\x13.app.WriteSetStruct*1\n\tOperation\x12\t\n\x05QUERY\x10\x00\x12\x0b\n\x07\x44\x45POSIT\x10\x01\x12\x0c\n\x08WITHDRAW\x10\x02*1\n\nReturnCode\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\x12\t\n\x05\x45RROR\x10\x02*&\n\nSourceType\x12\x0c\n\x08\x43USTOMER\x10\x00\x12\n\n\x06\x42RANCH\x10\x01\x32\xcf\x01\n\x07\x42\x61nking\x12\x42\n\x0bMsgDelivery\x12\x17.app.MsgDeliveryRequest\x1a\x18.app.MsgDeliveryResponse\"\x00\x12@\n\x0fRequestWriteSet\x12\x14.app.WriteSetRequest\x1a\x15.app.WriteSetResponse\"\x00\x12>\n\rCheckWriteSet\x12\x14.app.WriteSetRequest\x1a\x15.app.CheckSetResponse\"\x00\x62\x06proto3'
)

_OPERATION = _descriptor.EnumDescriptor(
  name='Operation',
  full_name='app.Operation',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='QUERY', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DEPOSIT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WITHDRAW', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=536,
  serialized_end=585,
)
_sym_db.RegisterEnumDescriptor(_OPERATION)

Operation = enum_type_wrapper.EnumTypeWrapper(_OPERATION)
_RETURNCODE = _descriptor.EnumDescriptor(
  name='ReturnCode',
  full_name='app.ReturnCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAILURE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=587,
  serialized_end=636,
)
_sym_db.RegisterEnumDescriptor(_RETURNCODE)

ReturnCode = enum_type_wrapper.EnumTypeWrapper(_RETURNCODE)
_SOURCETYPE = _descriptor.EnumDescriptor(
  name='SourceType',
  full_name='app.SourceType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CUSTOMER', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BRANCH', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=638,
  serialized_end=676,
)
_sym_db.RegisterEnumDescriptor(_SOURCETYPE)

SourceType = enum_type_wrapper.EnumTypeWrapper(_SOURCETYPE)
QUERY = 0
DEPOSIT = 1
WITHDRAW = 2
SUCCESS = 0
FAILURE = 1
ERROR = 2
CUSTOMER = 0
BRANCH = 1



_WRITESETSTRUCT = _descriptor.Descriptor(
  name='WriteSetStruct',
  full_name='app.WriteSetStruct',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='S_ID', full_name='app.WriteSetStruct.S_ID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ProgrID', full_name='app.WriteSetStruct.ProgrID', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=69,
)


_WRITESETREQUEST = _descriptor.Descriptor(
  name='WriteSetRequest',
  full_name='app.WriteSetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='S_ID', full_name='app.WriteSetRequest.S_ID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='LAST_ID', full_name='app.WriteSetRequest.LAST_ID', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Clock', full_name='app.WriteSetRequest.Clock', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=134,
)


_CHECKSETRESPONSE = _descriptor.Descriptor(
  name='CheckSetResponse',
  full_name='app.CheckSetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='IS_LAST', full_name='app.CheckSetResponse.IS_LAST', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=171,
)


_WRITESETRESPONSE = _descriptor.Descriptor(
  name='WriteSetResponse',
  full_name='app.WriteSetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Clock', full_name='app.WriteSetResponse.Clock', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='S_ID', full_name='app.WriteSetResponse.S_ID', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ProgrID', full_name='app.WriteSetResponse.ProgrID', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=237,
)


_MSGDELIVERYREQUEST = _descriptor.Descriptor(
  name='MsgDeliveryRequest',
  full_name='app.MsgDeliveryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='REQ_ID', full_name='app.MsgDeliveryRequest.REQ_ID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='OP', full_name='app.MsgDeliveryRequest.OP', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Amount', full_name='app.MsgDeliveryRequest.Amount', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='S_TYPE', full_name='app.MsgDeliveryRequest.S_TYPE', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='S_ID', full_name='app.MsgDeliveryRequest.S_ID', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='D_ID', full_name='app.MsgDeliveryRequest.D_ID', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Clock', full_name='app.MsgDeliveryRequest.Clock', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ProgrID', full_name='app.MsgDeliveryRequest.ProgrID', index=7,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=396,
)


_MSGDELIVERYRESPONSE = _descriptor.Descriptor(
  name='MsgDeliveryResponse',
  full_name='app.MsgDeliveryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='REQ_ID', full_name='app.MsgDeliveryResponse.REQ_ID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RC', full_name='app.MsgDeliveryResponse.RC', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Amount', full_name='app.MsgDeliveryResponse.Amount', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Clock', full_name='app.MsgDeliveryResponse.Clock', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='WriteID', full_name='app.MsgDeliveryResponse.WriteID', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=399,
  serialized_end=534,
)

_MSGDELIVERYREQUEST.fields_by_name['OP'].enum_type = _OPERATION
_MSGDELIVERYRESPONSE.fields_by_name['RC'].enum_type = _RETURNCODE
_MSGDELIVERYRESPONSE.fields_by_name['WriteID'].message_type = _WRITESETSTRUCT
DESCRIPTOR.message_types_by_name['WriteSetStruct'] = _WRITESETSTRUCT
DESCRIPTOR.message_types_by_name['WriteSetRequest'] = _WRITESETREQUEST
DESCRIPTOR.message_types_by_name['CheckSetResponse'] = _CHECKSETRESPONSE
DESCRIPTOR.message_types_by_name['WriteSetResponse'] = _WRITESETRESPONSE
DESCRIPTOR.message_types_by_name['MsgDeliveryRequest'] = _MSGDELIVERYREQUEST
DESCRIPTOR.message_types_by_name['MsgDeliveryResponse'] = _MSGDELIVERYRESPONSE
DESCRIPTOR.enum_types_by_name['Operation'] = _OPERATION
DESCRIPTOR.enum_types_by_name['ReturnCode'] = _RETURNCODE
DESCRIPTOR.enum_types_by_name['SourceType'] = _SOURCETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WriteSetStruct = _reflection.GeneratedProtocolMessageType('WriteSetStruct', (_message.Message,), {
  'DESCRIPTOR' : _WRITESETSTRUCT,
  '__module__' : 'banking_pb2'
  # @@protoc_insertion_point(class_scope:app.WriteSetStruct)
  })
_sym_db.RegisterMessage(WriteSetStruct)

WriteSetRequest = _reflection.GeneratedProtocolMessageType('WriteSetRequest', (_message.Message,), {
  'DESCRIPTOR' : _WRITESETREQUEST,
  '__module__' : 'banking_pb2'
  # @@protoc_insertion_point(class_scope:app.WriteSetRequest)
  })
_sym_db.RegisterMessage(WriteSetRequest)

CheckSetResponse = _reflection.GeneratedProtocolMessageType('CheckSetResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHECKSETRESPONSE,
  '__module__' : 'banking_pb2'
  # @@protoc_insertion_point(class_scope:app.CheckSetResponse)
  })
_sym_db.RegisterMessage(CheckSetResponse)

WriteSetResponse = _reflection.GeneratedProtocolMessageType('WriteSetResponse', (_message.Message,), {
  'DESCRIPTOR' : _WRITESETRESPONSE,
  '__module__' : 'banking_pb2'
  # @@protoc_insertion_point(class_scope:app.WriteSetResponse)
  })
_sym_db.RegisterMessage(WriteSetResponse)

MsgDeliveryRequest = _reflection.GeneratedProtocolMessageType('MsgDeliveryRequest', (_message.Message,), {
  'DESCRIPTOR' : _MSGDELIVERYREQUEST,
  '__module__' : 'banking_pb2'
  # @@protoc_insertion_point(class_scope:app.MsgDeliveryRequest)
  })
_sym_db.RegisterMessage(MsgDeliveryRequest)

MsgDeliveryResponse = _reflection.GeneratedProtocolMessageType('MsgDeliveryResponse', (_message.Message,), {
  'DESCRIPTOR' : _MSGDELIVERYRESPONSE,
  '__module__' : 'banking_pb2'
  # @@protoc_insertion_point(class_scope:app.MsgDeliveryResponse)
  })
_sym_db.RegisterMessage(MsgDeliveryResponse)



_BANKING = _descriptor.ServiceDescriptor(
  name='Banking',
  full_name='app.Banking',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=679,
  serialized_end=886,
  methods=[
  _descriptor.MethodDescriptor(
    name='MsgDelivery',
    full_name='app.Banking.MsgDelivery',
    index=0,
    containing_service=None,
    input_type=_MSGDELIVERYREQUEST,
    output_type=_MSGDELIVERYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RequestWriteSet',
    full_name='app.Banking.RequestWriteSet',
    index=1,
    containing_service=None,
    input_type=_WRITESETREQUEST,
    output_type=_WRITESETRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CheckWriteSet',
    full_name='app.Banking.CheckWriteSet',
    index=2,
    containing_service=None,
    input_type=_WRITESETREQUEST,
    output_type=_CHECKSETRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BANKING)

DESCRIPTOR.services_by_name['Banking'] = _BANKING

# @@protoc_insertion_point(module_scope)
